# golangci-lint configuration
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters-settings:
  lll:
    line-length: 100
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 100
    statements: 50

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace
