// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blocks.sql

package sqlcgen

import (
	"context"
)

const getBlockByNumber = `-- name: GetBlockByNumber :one
SELECT number, timestamp FROM blocks WHERE number = $1
`

func (q *Queries) GetBlockByNumber(ctx context.Context, number int64) (*Block, error) {
	row := q.db.QueryRowContext(ctx, getBlockByNumber, number)
	var i Block
	err := row.Scan(&i.Number, &i.Timestamp)
	return &i, err
}
