// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pancake_v2.sql

package sqlcgen

import (
	"context"
)

const addPancakeV2Pool = `-- name: AddPancakeV2Pool :exec
INSERT INTO pancake_v2_pools (address, token0, token1) VALUES ($1, $2, $3)
`

type AddPancakeV2PoolParams struct {
	Address string `json:"address"`
	Token0  string `json:"token0"`
	Token1  string `json:"token1"`
}

func (q *Queries) AddPancakeV2Pool(ctx context.Context, arg AddPancakeV2PoolParams) error {
	_, err := q.db.ExecContext(ctx, addPancakeV2Pool, arg.Address, arg.Token0, arg.Token1)
	return err
}

const countPancakeV2Pools = `-- name: CountPancakeV2Pools :one
SELECT COUNT(*) FROM pancake_v2_pools
`

func (q *Queries) CountPancakeV2Pools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPancakeV2Pools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllPancakeV2Pools = `-- name: GetAllPancakeV2Pools :many
SELECT address, token0, token1 FROM pancake_v2_pools
ORDER BY address
LIMIT $1 OFFSET $2
`

type GetAllPancakeV2PoolsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllPancakeV2Pools(ctx context.Context, arg GetAllPancakeV2PoolsParams) ([]*PancakeV2Pool, error) {
	rows, err := q.db.QueryContext(ctx, getAllPancakeV2Pools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PancakeV2Pool
	for rows.Next() {
		var i PancakeV2Pool
		if err := rows.Scan(&i.Address, &i.Token0, &i.Token1); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
