// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	AddBlock(ctx context.Context, arg AddBlockParams) error
	GetBlockByNumber(ctx context.Context, number int64) (*Block, error)
}

var _ Querier = (*Queries)(nil)
