// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: raw_txs.sql

package sqlcgen

import (
	"context"
)

const addRawTx = `-- name: AddRawTx :exec
INSERT INTO raw_txs (
    hash,
    from_address,
    to_address,
    value,
    timestamp,
    block_number,
    input_data,
    gas_used,
    max_gas_price
)
VALUES (
    $1::VARCHAR(255),
    $2::VARCHAR(255),
    $3::VARCHAR(255),
    $4::VARCHAR(255),
    $5::BIGINT,
    $6::BIGINT,
    $7::VARCHAR(255),
    $8::VARCHAR(255),
    $9::VARCHAR(255)
)
`

type AddRawTxParams struct {
	Hash        string `json:"hash"`
	FromAddress string `json:"from_address"`
	ToAddress   string `json:"to_address"`
	Value       string `json:"value"`
	Timestamp   int64  `json:"timestamp"`
	BlockNumber int64  `json:"block_number"`
	InputData   string `json:"input_data"`
	GasUsed     string `json:"gas_used"`
	MaxGasPrice string `json:"max_gas_price"`
}

func (q *Queries) AddRawTx(ctx context.Context, arg AddRawTxParams) error {
	_, err := q.db.ExecContext(ctx, addRawTx,
		arg.Hash,
		arg.FromAddress,
		arg.ToAddress,
		arg.Value,
		arg.Timestamp,
		arg.BlockNumber,
		arg.InputData,
		arg.GasUsed,
		arg.MaxGasPrice,
	)
	return err
}
