// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sushiswap_v2.sql

package sqlcgen

import (
	"context"
)

const addSushiSwapV2Pool = `-- name: AddSushiSwapV2Pool :exec
INSERT INTO sushiswap_v2_pools (address, token0, token1)
VALUES ($1, $2, $3)
`

type AddSushiSwapV2PoolParams struct {
	Address string `json:"address"`
	Token0  string `json:"token0"`
	Token1  string `json:"token1"`
}

func (q *Queries) AddSushiSwapV2Pool(ctx context.Context, arg AddSushiSwapV2PoolParams) error {
	_, err := q.db.ExecContext(ctx, addSushiSwapV2Pool, arg.Address, arg.Token0, arg.Token1)
	return err
}

const countSushiSwapV2Pools = `-- name: CountSushiSwapV2Pools :one
SELECT COUNT(*) FROM sushiswap_v2_pools
`

func (q *Queries) CountSushiSwapV2Pools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSushiSwapV2Pools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllSushiSwapV2Pools = `-- name: GetAllSushiSwapV2Pools :many
SELECT address, token0, token1 FROM sushiswap_v2_pools
ORDER BY address
LIMIT $1 OFFSET $2
`

type GetAllSushiSwapV2PoolsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllSushiSwapV2Pools(ctx context.Context, arg GetAllSushiSwapV2PoolsParams) ([]*SushiswapV2Pool, error) {
	rows, err := q.db.QueryContext(ctx, getAllSushiSwapV2Pools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SushiswapV2Pool
	for rows.Next() {
		var i SushiswapV2Pool
		if err := rows.Scan(&i.Address, &i.Token0, &i.Token1); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
