// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sushiswap_v3.sql

package sqlcgen

import (
	"context"
)

const addSushiSwapV3Pool = `-- name: AddSushiSwapV3Pool :exec
INSERT INTO sushiswap_v3_pools (address, token0, token1, fee, tick_spacing)
VALUES ($1, $2, $3, $4, $5)
`

type AddSushiSwapV3PoolParams struct {
	Address     string `json:"address"`
	Token0      string `json:"token0"`
	Token1      string `json:"token1"`
	Fee         string `json:"fee"`
	TickSpacing string `json:"tick_spacing"`
}

func (q *Queries) AddSushiSwapV3Pool(ctx context.Context, arg AddSushiSwapV3PoolParams) error {
	_, err := q.db.ExecContext(ctx, addSushiSwapV3Pool,
		arg.Address,
		arg.Token0,
		arg.Token1,
		arg.Fee,
		arg.TickSpacing,
	)
	return err
}

const countSushiSwapV3Pools = `-- name: CountSushiSwapV3Pools :one
SELECT COUNT(*) FROM sushiswap_v3_pools
`

func (q *Queries) CountSushiSwapV3Pools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSushiSwapV3Pools)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllSushiSwapV3Pools = `-- name: GetAllSushiSwapV3Pools :many
SELECT address, token0, token1, fee, tick_spacing FROM sushiswap_v3_pools
ORDER BY address
LIMIT $1 OFFSET $2
`

type GetAllSushiSwapV3PoolsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllSushiSwapV3Pools(ctx context.Context, arg GetAllSushiSwapV3PoolsParams) ([]*SushiswapV3Pool, error) {
	rows, err := q.db.QueryContext(ctx, getAllSushiSwapV3Pools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SushiswapV3Pool
	for rows.Next() {
		var i SushiswapV3Pool
		if err := rows.Scan(
			&i.Address,
			&i.Token0,
			&i.Token1,
			&i.Fee,
			&i.TickSpacing,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
