// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: uniswap_v2.sql

package sqlcgen

import (
	"context"
)

const addUniswapV2Pool = `-- name: AddUniswapV2Pool :exec
INSERT INTO uniswap_v2_pools (address, token0, token1) VALUES ($1, $2, $3)
`

type AddUniswapV2PoolParams struct {
	Address string `json:"address"`
	Token0  string `json:"token0"`
	Token1  string `json:"token1"`
}

func (q *Queries) AddUniswapV2Pool(ctx context.Context, arg AddUniswapV2PoolParams) error {
	_, err := q.db.ExecContext(ctx, addUniswapV2Pool, arg.Address, arg.Token0, arg.Token1)
	return err
}
