// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: uniswap_v3.sql

package sqlcgen

import (
	"context"
)

const addUniswapV3Pool = `-- name: AddUniswapV3Pool :exec
INSERT INTO uniswap_v3_pools (address, token0, token1, fee, tick_spacing)
VALUES ($1, $2, $3, $4, $5)
`

type AddUniswapV3PoolParams struct {
	Address     string `json:"address"`
	Token0      string `json:"token0"`
	Token1      string `json:"token1"`
	Fee         string `json:"fee"`
	TickSpacing string `json:"tick_spacing"`
}

func (q *Queries) AddUniswapV3Pool(ctx context.Context, arg AddUniswapV3PoolParams) error {
	_, err := q.db.ExecContext(ctx, addUniswapV3Pool,
		arg.Address,
		arg.Token0,
		arg.Token1,
		arg.Fee,
		arg.TickSpacing,
	)
	return err
}
